import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { SidebarProvider } from '~/app/_context/Sidebar';
import { ThemeProvider } from '~/app/_context/Theme';
import { Navbar } from "~/app/_components/Navbar";
import "assets/css/main.css";



export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <SidebarProvider>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
          </SidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
